build:
  services:
  - docker:1.11-dind
  image: docker:1.11
  script:
  - apk add -U make git
  - docker login --username gitlab-ci-token --password $CI_BUILD_TOKEN registry.gitlab.com
  - make build
  - make publish
  - docker logout
