#!/bin/bash

source /etc/rbenvrc

if [ -d ${HOME}/bin ]; then
    export PATH=${HOME}/bin:${PATH}
fi

gitlab_start() {
    echo $TZ | sudo tee /etc/timezone >/dev/null
    dpkg-reconfigure tzdata
    sudo sed -i "s|^#\s*${LANG/\./\\.}|  ${LANG}|" /etc/locale.gen
    sudo locale-gen

    src_dir=/home/git/src
    src_files=($(shopt -s nullglob; shopt -s dotglob; echo ${src_dir}/*))
    if [ ${#src_files[@]} -lt 1 ]; then
        echo -e "WARNING: First run - may take awhile\n"

        mkdir -p ${src_dir}
        cd ${src_dir}
        git clone https://gitlab.com/gitlab-org/gitlab-development-kit.git .
        make
    fi

    rm ${src_dir}/postgresql/.s.PGSQL*
    rm ${src_dir}/postgresql/data/postmaster.pid

    echo -e "\033[31;1mGITLAB development container started!\033[37;0m\n"

    echo "You can now setup and start gitlab."
    echo -e "Run: \033[1mgitlab help\033[0m for more details"


    echo "Gitlab will be available at:"
    echo "  url: http://172.17.42.1/"
    echo " user: root"
    echo " pass: 5iveL!fe"

    cd ${src_dir}
    /usr/local/bin/run_bash
}

case "$1" in
    start)
        gitlab_start
        ;;
    *)
        if [ -x $1 ]; then
            $1
        else
            prog=$(which $1)
            if [ -n "${prog}" ] ; then
                shift 1
                $prog $@
            else
                exit 255
            fi
        fi
        ;;
esac
