#!/bin/bash

if [ -d ${HOME}/bin ]; then
    export PATH=${HOME}/bin:${PATH}
fi

export TERM=xterm

alias brspec="bundle exec rspec --format=documentation"
alias brake="bundle exec rake"

if [ "$#" -gt 0 ]; then
    source /etc/rbenvrc

    prog=$(which $1)
    if [ -n "${prog}" ]; then
        shift 1
        $prog $@
    else
        exit 255
    fi
else
    /bin/bash
fi
