#!/bin/bash

set -e

check_env() {
    if [ -z ${2} ]; then
        echo "Error! ${1} not specified!"
        exit 1
    else
        echo "Building image with ${1}=${2}"
    fi
}

check_env 'RUBY_VERSION' ${RUBY_VERSION}
check_env 'PHANTOM_JS_VERSION' ${PHANTOM_JS_VERSION}

# Prepare system for rbenv and ruby
apt-get install -y build-essential zlib1g-dev libssl-dev libreadline-dev \
                   libyaml-dev libxml2-dev libxslt-dev libffi-dev        \
                   libmysqlclient-dev                                    \
                   git net-tools openssh-server openssh-client

# Install gitlab stack
apt-get install -y postgresql libpq-dev redis-server libicu-dev ed cmake \
                   g++ nodejs libkrb5-dev golang nginx pkg-config

# Install rbenv
git clone https://github.com/sstephenson/rbenv.git /usr/local/rbenv
mkdir -p /usr/local/rbenv/plugins
git clone https://github.com/sstephenson/ruby-build.git /usr/local/rbenv/plugins/ruby-build
cd /usr/local/rbenv/plugins/ruby-build
./install.sh

echo "gem: --no-rdoc --no-ri" >> /etc/skel/.gemrc
echo "gem: --no-rdoc --no-ri" >> /root/.gemrc
echo "source /etc/rbenvrc"    >> /etc/skel/.bashrc
echo "source /etc/rbenvrc"    >> /root/.bashrc
echo "export RBENV_ROOT=\"/usr/local/rbenv\""  >> /etc/rbenvrc
echo "export PATH=\"\$RBENV_ROOT/bin:\$PATH\"" >> /etc/rbenvrc
echo "eval \"\$(rbenv init -)\""               >> /etc/rbenvrc

export CONFIGURE_OPTS="--disable-install-doc"

# Add development user
addgroup rbenv
useradd -d /home/git -m -s /bin/bash -G rbenv git
adduser git sudo

# Install ruby
bash -l -c "source /etc/rbenvrc && rbenv install ${RUBY_VERSION} && rbenv global ${RUBY_VERSION} && gem install bundler"
chgrp rbenv -R /usr/local/rbenv
chmod g+w   -R /usr/local/rbenv

# Install phantomjs
cd /tmp
wget -q "https://bitbucket.org/ariya/phantomjs/downloads/${PHANTOM_JS_VERSION}.tar.bz2"
tar -xvjf ${PHANTOM_JS_VERSION}.tar.bz2
mv ${PHANTOM_JS_VERSION} /usr/local/share
ln -s /usr/local/share/${PHANTOM_JS_VERSION}/bin/phantomjs /usr/local/bin
phantomjs --version

# Cleanup
apt-get clean
rm -rf /tmp/*
rm -rf /var/lib/apt/lists/*
